.eslintignore, .eslintrc.json, .gitignore, package.json, src/__tests__/monzo.spec.ts, src/__tests__/scale-workshop-2.spec.ts, src/index.ts, src/monzo.ts, src/scale-workshop-2-parser.ts, src/scale-workshop-2.pegjs, tsconfig.json
Implement parsing for Scale Workshop 2 lines.
=> Add time exponent to the monzo class

src/__tests__/parser.spec.ts, src/builtin.ts, src/monzo.ts
Implement builtin constant structure detector.
=> Implement stdlib alternating sequence generation

scripts/builtin-docs.ts, src/__tests__/parser/expression.spec.ts, src/__tests__/parser/source.spec.ts, src/__tests__/sonic-weave-ast.spec.ts, src/ast.ts, src/builtin.ts, src/parser.ts, src/sonic-weave.pegjs
=> Implement spread and rest syntax

package-lock.json, src/__tests__/monzo.spec.ts, src/__tests__/parser/expression.spec.ts, src/__tests__/parser/stdlib.spec.ts, src/interval.ts, src/monzo.ts, src/parser.ts
=> More accurate logdivision

BUILTIN.md, src/__tests__/parser/expression.spec.ts, src/builtin.ts, src/context.ts, src/interval.ts, src/parser.ts
=> Dedicated val type

README.md, src/COMMAS.md, src/__tests__/parser/expression.spec.ts, src/expression.ts, src/extra-commas.ts, src/fjs.ts, src/sonic-weave.pegjs
=> Add more inflection flavors to FJS

src/__tests__/parser/expression.spec.ts, src/__tests__/parser/source.spec.ts, src/ast.ts, src/builtin.ts, src/parser.ts, src/sonic-weave.pegjs
=> Implement nested destructuring

BUILTIN.md, README.md, scripts/builtin-docs.ts, src/__tests__/parser/expression.spec.ts, src/__tests__/parser/source.spec.ts, src/__tests__/parser/stdlib.spec.ts, src/__tests__/sonic-weave-ast.spec.ts, src/ast.ts, src/builtin.ts, src/parser.ts, src/sonic-weave.pegjs
=> Implement default values for parameters

src/__tests__/words.spec.ts, src/index.ts, src/words.ts
=> Implement abstract step vectors

BUILTIN.md, src/__tests__/parser/expression.spec.ts, src/builtin.ts, src/words.ts
See https://en.xen.wiki/w/User:Frostburn/Step_Label_Spectrum for my reasoning.
ref #165
=> Implement scale step string calculation

src/ast.ts, src/interval.ts, src/monzo.ts
=> Add type documentation for the Interval and Val classes

src/__tests__/sonic-weave-ast.spec.ts, src/sonic-weave.pegjs
=> Make spaces mandatory with labeling

src/__tests__/words.spec.ts, src/utils.ts, src/words.ts
Add a default parameter to getStepVector() implied by the tests.
=> Fix step vector behavior with pathological keys

README.md, src/__tests__/parser/expression.spec.ts, src/pythagorean.ts, src/sonic-weave.pegjs
Implement missing eight-sharps, quarter-minor intervals etc.
=> Fix formatting of P5 % 8

src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/chord-parser.ts, src/parser/expression.ts, src/parser/index.ts, src/parser/statement.ts, src/stdlib/builtin.ts
Make visitor.getCurrentScale() into a plain getter.
ref #146
=> Be more conservative about the public API of ExpressionVisitor

src/__tests__/monzo.spec.ts, src/expression.ts, src/grammars/base.pegjs, src/grammars/sonic-weave.pegjs, src/interval.ts, src/monzo.ts, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/chord-parser.ts, src/parser/expression.ts, src/stdlib/builtin.ts, src/warts.ts
Change prime limit syntax from 12@5 to 12@.5
ref #214
=> Admit s, Hz, rc and negative fractions in monzo basis

src/__tests__/interval.spec.ts, src/__tests__/monzo.spec.ts, src/__tests__/pythagorean.spec.ts, src/__tests__/scale-workshop-2.spec.ts, src/context.ts, src/expression.ts, src/extra-commas.ts, src/fjs.ts, src/grammars/sonic-weave.pegjs, src/interval.ts, src/monzo.ts, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/__tests__/tag.spec.ts, src/parser/expression.ts, src/parser/statement.ts, src/scale-workshop-2-parser.ts, src/stdlib/builtin.ts, src/stdlib/runtime.ts, src/tools.ts, src/utils.ts, src/warts.ts, src/words.ts
Make edosteps abstract and move to Interval class
ref #229
=> Separate radical and real concerns

src/ast.ts, src/grammars/sonic-weave.pegjs, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/sonic-weave-ast.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/expression.ts, src/stdlib/prelude.ts
Define intrinsic semantics for implicit calls.
ref #252
=> Replace labeling with implicit calling

README.md, documentation/intermediate-dsl.md, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/expression.ts, src/parser/parser.ts, src/parser/statement.ts
Makes context corruption less likely.
=> Tweak default type-based actions

src/parser/__tests__/expression.spec.ts, src/parser/__tests__/vector-broadcasting.spec.ts, src/parser/expression.ts
Apply rules to implicit mapping.
ref #260
=> Define prototypical vector broadcasting rules

src/fjs.ts, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/__tests__/vector-broadcasting.spec.ts, src/parser/expression.ts, src/stdlib/builtin.ts, src/stdlib/prelude.ts, src/stdlib/public.ts, src/stdlib/runtime.ts
=> Apply broadcasting rules to most unary built-in functions

README.md, documentation/technical.md, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/sonic-weave-ast.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/expression.ts
=> Switch lest operands; remove irrelevant tests

documentation/technical.md, src/grammars/sonic-weave.pegjs, src/parser/__tests__/expression.spec.ts
Add a note about lest associativity.
=> Remove lest assignment due to no change possible

documentation/BUILTIN.md, src/parser/__tests__/vector-broadcasting.spec.ts, src/stdlib/prelude.ts
ref https://github.com/xenharmonic-devs/scale-workshop/issues/675
=> Implement weilHeight utility

package-lock.json, package.json, src/__tests__/monzo.spec.ts, src/monzo.ts
Update xen-dev-utils dependency.
ref #288
=> Implement JSON (de)serialization of TimeMonzo and TimeReal

documentation/advanced-dsl.md, documentation/intermediate-dsl.md, documentation/technical.md, src/ast.ts, src/expression.ts, src/grammars/base.pegjs, src/grammars/sonic-weave.pegjs, src/interval.ts, src/monzo.ts, src/parser/__tests__/expression.spec.ts, src/parser/expression.ts, src/pythagorean.ts, src/stdlib/builtin.ts, src/stdlib/prelude.ts, src/utils.ts, src/warts.ts
Add support in subgroup basis too.
ref #301
=> Add support for unary √

documentation/BUILTIN.md, documentation/advanced-dsl.md, documentation/intermediate-dsl.md, documentation/technical.md, examples/hexany.sw, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/expression.ts, src/parser/statement.ts, src/stdlib/builtin.ts, src/stdlib/prelude.ts, src/stdlib/public.ts, src/stdlib/runtime.ts
Favor creating copies.
Favor popping the pre-existing scale.
ref #256
=> Tweak stdlib semantics to remove past tense verbs

documentation/BUILTIN.md, documentation/advanced-dsl.md, documentation/technical.md, documentation/tempering.md, src/__tests__/interval.spec.ts, src/ast.ts, src/expression.ts, src/grammars/sonic-weave.pegjs, src/interval.ts, src/monzo.ts, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/sonic-weave-ast.spec.ts, src/parser/__tests__/source.spec.ts, src/parser/__tests__/stdlib.spec.ts, src/parser/__tests__/vector-broadcasting.spec.ts, src/parser/chord-parser.ts, src/parser/expression.ts, src/stdlib/builtin.ts, src/stdlib/public.ts, src/stdlib/runtime.ts, src/warts.ts
Clarify AST hierarchy for cologarithmic nodes.
Implement conversion between val formats.
ref #353
=> Make (val) subgroup basis a primitive value

documentation/BUILTIN.md, documentation/advanced-dsl.md, examples/jubilismic-gs.sw, examples/marveldene.sw, examples/semitonismic-gs.sw, package-lock.json, package.json, src/__tests__/interval.spec.ts, src/__tests__/temper.spec.ts, src/interval.ts, src/monzo.ts, src/parser/__tests__/source.spec.ts, src/stdlib/builtin.ts, src/temper.ts
=> Implement methods for obtaining TE optimal tuning maps

documentation/intermediate-dsl.md, documentation/technical.md, src/ast.ts, src/grammars/sonic-weave.pegjs, src/parser/__tests__/expression.spec.ts, src/parser/__tests__/poor-grammar.spec.ts, src/parser/__tests__/vector-broadcasting.spec.ts, src/parser/expression.ts, src/stdlib/runtime.ts
=> Implement pythonic 1 < x < 2

documentation/BUILTIN.md, src/parser/__tests__/formatting.spec.ts, src/stdlib/builtin/index.ts, src/stdlib/public.ts
=> Implement best effort short string formatting

documentation/BUILTIN.md, src/parser/__tests__/temper.spec.ts, src/parser/expression.ts, src/stdlib/builtin/temper.ts
Admit containers as spread arguments.
ref #422
=> Accept lone vals for commaBasis and mappingBasis

src/grammars/sonic-weave.pegjs, src/parser/__tests__/sonic-weave-ast.spec.ts
=> Require accidentals with signed absolute FJS octaves

AUTHORS, README.md, documentation/BUILTIN.md, src/parser/__tests__/stdlib.spec.ts, src/stdlib/prelude.ts
Here are basic tests, I don’t know what else to check while not rigidly checking for too much.
Also includes additions to the README and vanity fixes.
=> Add `isoharmonic` and `isorescale` functions to the library
